---
- name: Install MySQL
  yum:
    name: "{{ item }}"
    state: present
  with_items:
     - "mysql"
     - "mysql-server"
  when: ansible_distribution == "Amazon"

- name: Install MariaDB
  yum:
    name: "{{ item }}"
    state: present
  with_items:
     - "mariadb"
     - "mariadb-server"
  when: ansible_distribution == "CentOS"


- name: Install MySQLDB python package for secure installations.
  yum:
    name: MySQL-python27
    state: present
  when: ansible_distribution == "Amazon"

- name: Install MySQLDB python package for secure installations.
  yum:
    name: MySQL-python
    state: present
  when: ansible_distribution == "CentOS"
