---
- name: restart mysql
  service: 
     name: mysqld
     state: restarted
  when: ansible_distribution == "Amazon"

- name: restart mysql
  service: 
     name: mariadb
     state: restarted
  when: ansible_distribution == "CentOS"
